### PR TITLE
Handle signals and gracefully shut down

### PR DESCRIPTION
**Pull request by JonathonReinhart**
Handle SIGINT, SIGQUIT, and SIGTERM by gracefully shutting down.

This PR is a result of discussions on #13 and is based loosely on grafana#11.

Follows #15.

### CODE REVIEW

**Comment by decke** [comment]
I would first like to have an opinion from @chrj because I think this would be useful for smtpd.

**Comment by JonathonReinhart** [comment]
I just realized that while this does wait for the listener goroutines to exit, it probably doesn't wait for any open client connections to complete. To do that would require code in https://github.com/chrj/smtpd as mentioned in chrj/smtpd#10. If I have time I may put a PR together for that project. However, if that doesn't land, it's probably still worthwhile to merge this before `smtpd.Server` gets a `Shutdown()` method.

**Comment by JonathonReinhart** [comment]
Update: I submitted https://github.com/chrj/smtpd/pull/11. If that gets merged, I'll need to update this to call `Shutdown()`.

**Comment by JonathonReinhart** [comment]
Closing in favor of #22.

**Pull request closed without merging**
