### PR TITLE
Allow ignoring an insecure tls connection

### PR DESCRIPTION
**Pull request by NoUseFreak**
This change allows to ignore an insecure connection.

### CODE REVIEW

**Review by decke — CHANGES_REQUESTED** [review]
4 out of 5 commits are Docker related. This does not look like it was intended.

**Comment by NoUseFreak** [comment]
Update the PR to only include skip logic

**Review by decke — COMMENTED** [review]
Is there a specific reason why you only added it for starttls? Shouldn't it also be added for smtps?

**Review by decke — APPROVED** [review]

**Comment by NoUseFreak** [comment]
@decke What needs to be done in order to get this merged?

**Pull request merged**
