### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by Coronon**
This commit adds **docker support** to smtprelay.

I needed to run this between an isolated network and the hostile interwebs inside _docker-compose_, so after a bit of tinkering, this came about.

Please just review but don't merge yet, as I want to battle test this first :)

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
Thanks for the contribution, but #50 was already closed.

**Comment by Coronon** [comment]
There is a big difference: #50 wanted to automatically push to the public docker registry after each build. This only adds the ability to create your own image. As it is build directly always from the latest version, the isn't much "maintaining".

**Comment by decke** [comment]
@Coronon I do understand that people want to run smtprelay in a docker environment and I have no problems with that. I also plan to rewrite the config part in smtprelay to use [peterbourgon/ff](https://github.com/peterbourgon/ff) which now also supports .env files and environment variables. That should ease life in docker environments.

But I do not plan to provide any default Dockerfiles or prepared images. From what I have seen the people that want to run it in a docker environment are all capable of doing that since it's a straight forward Go project. The Dockerfiles that I have seen for smtprelay are all biased in some way and differ from what I would do. If someone thinks it's necessary then please create some unofficial docker image for your own use case like it seems to be common in this environments. Please also respect that I will not recommend any of those over any other.

**Comment by Coronon** [comment]
@decke Fair enough, still huge thanks for this awesome tool!

**Pull request closed without merging**
